# Generated by Django 2.2 on 2021-11-25 07:32

from django.db import migrations, models
import django.db.models.deletion
import msg.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='编号')),
                ('title', models.CharField(default='时代系列|新装限时上架', max_length=20, verbose_name='左侧标题')),
                ('time', models.CharField(default='11|11', max_length=10, verbose_name='日期')),
                ('classify', models.BooleanField(default=True, verbose_name='归类')),
                ('form', models.CharField(default='text', max_length=10, verbose_name='形式')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=msg.models.user_directory_path, verbose_name='图片')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='msg.Article', verbose_name='编号')),
            ],
        ),
    ]
