# Generated by Django 2.2 on 2021-11-25 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msg.Article', verbose_name='编号'),
        ),
    ]
